# Generated by Django 4.2.2 on 2023-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=122)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=122)),
                ('occupation', models.CharField(max_length=122)),
                ('IDtype', models.CharField(max_length=122)),
                ('IDnumber', models.CharField(max_length=122)),
                ('expirydate', models.DateField()),
                ('PermanentorTemporary', models.TextField()),
                ('state', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('father', models.CharField(max_length=122)),
                ('mother', models.CharField(max_length=122)),
                ('grandfather', models.CharField(max_length=122)),
                ('bloodgroup', models.CharField(max_length=122)),
                ('requirements', models.CharField(max_length=122)),
            ],
        ),
    ]
